### ISSUE TITLE
Add Wallet API

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/safe_app_csharp#101]
Tasks:
- Add bindings for all exposed in `safe-cli/safe_api_ffi/ffi/wallet.rs`.
- Add descriptive comments.
- Add unit tests

The Wallet APIs :
- [x] [wallet create](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/wallet.rs#L11)
- [x] [wallet insert](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/wallet.rs#L26)
- [x] [wallet balance](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/wallet.rs#L49)
- [x] [wallet get default balance](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/wallet.rs#L66)
- [x] [wallet transfer](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/wallet.rs#L88)
- [x] [wallet get](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/wallet.rs#L109)
- [x] Unit Tests

(Ensure all APIs from `safe-cli/src/api/wallet.rs` are present there.)

**Comment by vigneshwara044** [comment]
WIP branch: https://github.com/vigneshwara044/safe_app_csharp/tree/new-api-with-errors

**Comment by ravinderjangra** [comment]
closed by #114

**Comment by ravinderjangra** [comment]
Hey @vigneshwara044, some of the API may need to be updated after https://github.com/maidsafe/safe-cli/pull/261 is merged.
