### ISSUE TITLE
Add XOR-URL API

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/safe_app_csharp#103]
Tasks:
- Add bindings for all exposed in `safe-cli/safe_api_ffi/ffi/xorurl.rs`.
- Add descriptive comments.
- Add unit tests

The Wallet APIs :
- [x] [xorurl encode](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/xorurl.rs#L12)
- [x] [xorurl encoder](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/xorurl.rs#L53)
- [x] [xorurl encoder from url](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/xorurl.rs#L90)
- [x] Unit Tests

(Ensure all APIs from `safe-cli/src/api/xorurl` are present there.)

**Comment by ravinderjangra** [comment]
WIP branch: https://github.com/ravinderjangra/safe_app_csharp/tree/new-api-with-errors

**Comment by ravinderjangra** [comment]
closed by #108
