### ISSUE TITLE
Add Connect API

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/safe_app_csharp#105]
Tasks:
- Add bindings for all exposed in `safe-cli/safe_api_ffi/ffi/mod.rs`.
- Add descriptive comments.
- Add unit tests

The Wallet APIs :
- [x] [connect](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/mod.rs#L16)

- [x] Unit Tests

(Ensure all APIs from `safe-cli/src/api/mod.rs` are present there.)

**Comment by vigneshwara044** [comment]
WIP branch: https://github.com/ravinderjangra/safe_app_csharp/tree/new-api-with-errors

**Comment by ravinderjangra** [comment]
closed by #108
