### ISSUE TITLE
Add Files API

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/safe_app_csharp#106]
Tasks:
- Add bindings for all exposed in `safe-cli/safe_api_ffi/ffi/files.rs`.
- Add descriptive comments.
- Add unit tests

The Files APIs:
- [x] [files container create](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L12)
- [x] [files container get](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L48)
- [x] [files container sync](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L70)
- [x] [files container add](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L113)
- [x] [files container add from raw](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L149)
- [x] [files put published immuatable](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L186)
- [x] [files get published immuatable](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L206)

Passing rudimentary unit tests:
- [x] [files container create](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L12)
- [x] [files container get](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L48)
- [x] [files container sync](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L70)
- [x] [files container add](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L113)
- [x] [files container add from raw](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L149)
- [x] [files put published immuatable](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L186)
- [x] [files get published immuatable](https://github.com/ravinderjangra/safe-cli/blob/bindings/safe_api_ffi/ffi/files.rs#L206)

(Ensure all APIs from `safe-cli/src/api/files.rs` are present there.)

**Comment by ravinderjangra** [comment]
fixed by #116
