### ISSUE TITLE
IntPtr is passed with ref keyword giving `receiver is gone` error.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#111]
`IntPtr` is passed with `ref ` keyword, which gives the _address_ of the pointer and not the _value_ of it. This means that `_appPtr` is passed/stored incorrectly and when we attempt to send a message and interact with the network, the state is decoded incorrectly and it appears as if the `receiver is gone`.

**Comment by ravinderjangra** [comment]
fixed by #112.
