### ISSUE TITLE
Bindings: CreateNrsMapContainerAsync is not mapping values correctly

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#115]
The `FileContainer` is created using `CLI` (in absence of [Files API](https://github.com/maidsafe/safe_app_csharp/issues/106) in `safe_app_csharp`).
Linking through C# bindings is confirmed working when accessing the link through `CLI`.
However, the returned `NrsMap` from `CreateNrsMapContainerAsync` does not have the expected values:
 
- Field `SubNamesMap` is empty
- Field `Default` is null

**Comment by ravinderjangra** [comment]
I think the changes got lost somewhere when it was rebased. I'll update this in `safe-cli` master to use the Json string for the `nrs_map` for now. And once I have something working then I will update this to use structs instead of the Json string.

**Comment by ravinderjangra** [comment]
PR to fix this in C# side: https://github.com/oetyng/safe_app_csharp/pull/2.
Branch for cli-fix: https://github.com/maidsafe/safe-cli/compare/master...ravinderjangra:refactoring?expand=1

**Comment by ravinderjangra** [comment]
closed by #122
