### ISSUE TITLE
Update NRS API

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe_app_csharp#130]
`ParseAndResolveUrlNative` is using `FfiResultXorUrlEncoderBoolCb`, this needs to be updated with the latest bindings. Update the bindings to use `FfiResultXorUrlEncoderXorUrlEncoderCb`. Test the other API as well some similar changes.

**Comment by oetyng** [comment]
This was already updated in the NRS PR.

https://github.com/maidsafe/safe_app_csharp/blob/f5057cc872f0ad2728ffb9beb423832afe6e0e13/SafeApp/API/Nrs.cs#L35

It was fixed here: https://github.com/maidsafe/safe_app_csharp/commit/aa095fd926ad8232aa0fe79aba326be7de10d75d

The only thing is that the callback was never renamed to properly reflect this.

Sop it's only about renaming `FfiResultXorUrlEncoderBoolCb` to `FfiResultXorUrlEncoderXorUrlEncoderCb`

**Comment by oetyng** [comment]
Solved by #131
