### ISSUE TITLE
Use byte array instead of List<byte>

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#39]
Generally, in all places using List<byte>, it can be changed to byte array.
It will only be passed around, and required format when used again downstream, is byte[]. So there is is no reason to use a List for it.

https://github.com/maidsafe/safe_app_csharp/blob/a7843e241ab7fd7da2fb0466de8ceee667b7a88c/SafeApp/MData/MDataInfoActions.cs#L114

**Comment by ravinderjangra** [comment]
Thanks, @oetyng for the suggestion. Some code is generated using bindgen tool and wrapper code is written manually so we will discuss this and update accordingly.

**Comment by ravinderjangra** [comment]
closed by #88 and we need to ensure in all future changes that this is followed.
