### ISSUE TITLE
Update project settings to generate xml documentation files

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe_app_csharp#44]
Update project settings for following projects to generate XML files for documentation. These files will be shipped with DLLs in NuGet package to show documentation while using the APIs.

**Projects to update:**
- SafeApp
- SafeApp.Utilities
- SafeApp.MockAuthBindings
- SafeApp.MockAuthBindings.Desktop
- SafeApp.MockAuthBindings.Android
- SafeApp.MockAuthBindings.Desktop
- SafeApp.MockAuthBindings.iOS

**Comment by safesurfer** [comment]
QA verified
