### ISSUE TITLE
Add Separate Null Reference NativeHandle for Mutable Data Entries and Permissions

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe_app_csharp#51]
**Description:**
Currently, we have a NativeHandle named Zero which is used when we create a new mutable data with 0 entries or null PermissionSet. To make is scenario specific add separate NativeHandle for permissions, MData entries, MDataPermissions.

**Comment by safesurfer** [comment]
QA verified that NativeHandle Zero is deprecated and added separate NativeHandles to replace it.
