### ISSUE TITLE
Not working on Andorid when API level<23

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe_app_csharp#54]
The native library used for android `libsafe_app.so` for the architecture `armeabi-v7a` is currently not working on devices which have API level <`23`

Solution:
Re-built the `safe_app` native library from [safe_client_libs](https://github.com/maidsafe/safe_client_libs) with a toolchain having android api level 21 using `~/android-ndk/build/tools/make_standalone_toolchain.py --arch arm --api 21 --install-dir ~/toolchains/android-21-arm-toolchain`. And proceed with generating the native libs

**Comment by ashwinkumar6** [comment]
A new nuget package is to uploaded with the version `v0.2.1`

- Go to System's TempPath and delete the `nativelibs` folder
- Delete the `lib` folder in `safe_app_csharp\SafeApp.AppBindings.Android`
- Build Project in Release Mode
- generate the `MaidSafe.SafeApp`: nuget.exe pack SafeApp.nuspec ([Download](https://www.nuget.org/downloads) nuget.exe CLI)
- finally [publish](http://nuget.org/) the nuget.

**Comment by ravinderjangra** [comment]
hey @ashwinkumar6, please update the issue status for this issue as I think we have already fixed this when we update the native libs on S3. Please confirm and close(if solved).

**Comment by ashwinkumar6** [comment]
This issue has been resolved
