### ISSUE TITLE
Include Authenticator for non-Mock as well.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#56]
This is needed for applications that are not using Browser auth flow.

**Comment by ravinderjangra** [comment]
Hey @oetyng you can try and use [safe-authenticator-cli](https://github.com/maidsafe/safe-authenticator-cli) for authentication (no browser needed). It also provides option to run daemon in background. Also, check the [forum post](https://safenetforum.org/t/safe-authenticator-cli/28102) for more details.

**Comment by oetyng** [comment]
Hi @ravinderjangra
Thanks for the quick tip.
I realized that we could actually produce this out of available resources, into a format that would be much easier consumed in C#-applications.
So here it is now: https://github.com/oetyng/SAFE.AuthClient
