### ISSUE TITLE
Add Linux CI to build and run .NET Core tests

### ISSUE THREAD

**Issue by ravinderjangra** [maidsafe/safe_app_csharp#59]
Currently .NET Core project is built and run on Windows x64 and MacOS x64. Include Linux x64 build and test CI on the master branch.

**Comment by ravinderjangra** [comment]
As this needs to be done only on AzureDevops side so no PR is required:
**Changes:**
* Added new build pipeline in Azure DevOps to build and run .NET Core tests on Linux x64.
* Build fail in case of test failure and also the build for PR is enabled.
* Update README file to show the build status. PR (https://github.com/maidsafe/safe_app_csharp/pull/60)


Please verify @safesurfer and close the issue.

**Comment by safesurfer** [comment]
QA verified
