### ISSUE TITLE
Increase CodeCoverage by adding tests for SafeApp.MData

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe_app_csharp#62]
**Function/ attributes covered in this test**
- `Sha3HashAsync`
- `GenerateNonceAsync`
- `NewPrivateAsync`
- `SetUserPermissionsAsync`
- `GetAsync`
- `ListValuesAsync`
- `LenAsync`

**Scenario** 
- Use `Sha3HashAsync` to generate a deterministic XOR address.
- Use `GenerateNonceAsync` to generate a nonce 
- Create a private mutable data using the function `NewPrivateAsync` and previously generated nonce and XOR address
- Use `SetUserPermissionsAsync` to set permission for a user and get the list of MData permission using `GetAsync`
- Add entries to the MD
- Use `ListValuesAsync` and `LenAsync` to get the list of values from the MD and get the total number of entries respectively and verify accordingly

**Comment by safesurfer** [comment]
QA verified and checked that the above tests have been added and overall code coverage has been improved +4%
