### ISSUE TITLE
Increase CodeCoverage by adding tests for SafeApp.Sesssion

### ISSUE THREAD

**Issue by ashwinkumar6** [maidsafe/safe_app_csharp#63]
**Function/ attributes covered in this test**
- `OnDisconnected`
- `IsDisconnected`
- `ReconnectAsync`

**Scenario** 
- Use `TestSimulateNetworkDisconnectAsync` to mock the network disconnect.
- When the network is disconnected make sure the `OnDisconnected` event is fired.
- Use the `IsDisconnected` property to check if the network has been disconnected if yes, then reconnect using the `ReconnectAsync` method and make sure that the `IsDisconnected` property is false

**Comment by safesurfer** [comment]
QA verified and checked that the above tests have been added and overall code coverage has been improved +4%
