### ISSUE TITLE
Framework support updates

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#82]
- Discontinue support for .NET Core 1.x
- Add support for .NET Core 2.x
- Add support for .NET Core 3.0

.NET Core 1.x is hardly used by anyone I believe. It had some problems and many changes were made for 2.0. Currently it's 2.x that people use in production, and 3.0 is in late preview stages with official release planned for September 2019.

_**Note:** Needs further discussion_

**Comment by oetyng** [comment]
I upped the priority because for the library to actually be widely used, it is more or less required.

**Comment by ravinderjangra** [comment]
fixed by: #137
