### ISSUE TITLE
Fix ReSharper issues.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#85]
Fix (suppress or modify) following ReSharper issues:

- 12 `Constraint Violations `
- 7 `Potential Code Quality Issues`
- 277 `Spelling Issues`

This would help detect potentially valid issues.

_**Note**_: Among the `Potential Code Quality Issues`, there are "disable once" declarations, however they seem to not be regarded by ReSharper local code inspection.

**Comment by ravinderjangra** [comment]
We no longer use the CodeInspect, `JetBrains.Annotations` and Reshaper comments in the code.
