### ISSUE TITLE
Add Keys API

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#95]
Tasks:

- Add bindings for all exposed in `safe-cli/safe_api_ffi/ffi/keys.rs`.
- Add descriptive comments.
- Add rudimentary tests.

Implemented:
- [x] [generate_keypair](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L8)
- [x] [keys_create](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L26)
- [x] [keys_create_preload_test_coins](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L56)
- [x] [keys_balance_from_sk](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L82)
- [x] [keys_balance_from_url](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L99)
- [x] [validate_sk_for_url](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L118)
- [x] [keys_transfer](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L137)

Passing rudimentary test:
- [x] [generate_keypair](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L8)
- [x] [keys_create](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L26)
- [x] [keys_create_preload_test_coins](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L56)
- [x] [keys_balance_from_sk](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L82)
- [x] [keys_balance_from_url](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L99)
- [x] [validate_sk_for_url](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L118)
- [x] [keys_transfer](https://github.com/ravinderjangra/safe-cli/blob/ba0c2127de4cdc5518e2e681e4f96f71067ec593/safe_api_ffi/ffi/keys.rs#L137)

(Ensure all APIs from `safe-cli/src/api/keys.rs` are present there.)

**Comment by oetyng** [comment]
Solved by #109.

**Comment by ravinderjangra** [comment]
hey @oetyng, I think the `GenerateKeyPairAsync()` should be a static function. Because if you don't have an account or connection you can still generate a key pair.
https://github.com/maidsafe/safe_app_csharp/blob/vNext/SafeApp/API/Keys.cs#L28

**Use Case:**
I want you to add some balance to a key which then I will use to create an account.

We can open a separate issue for this you want.
