### ISSUE TITLE
Add NRS API

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe_app_csharp#96]
Tasks:

- Add bindings for all exposed in `safe-cli/safe_api_ffi/ffi/nrs.rs`.
- Add descriptive comments.
- Add unit tests.

Implemented:
- [x] [parse_url](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L8)
- [x] [parse_and_resolve_url](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L28)
- [x] [nrs_map_container_add](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L84)
- [x] [nrs_map_container_remove](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L125)
- [x] [nrs_map_container_get](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L157)

Passing rudimentary test:
- [x] [parse_url](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L8)
- [x] [parse_and_resolve_url](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L28)
- [x] [nrs_map_container_add](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L84)
- [x] [nrs_map_container_remove](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L125)
- [x] [nrs_map_container_get](https://github.com/ravinderjangra/safe-cli/blob/71afe069a61474e34c32fe5055a088626f959b3b/safe_api_ffi/ffi/nrs.rs#L157)

(Ensure all APIs from `safe-cli/src/api/nrs.rs` are present there.)

**Comment by ravinderjangra** [comment]
closed by #122
